version: '2.1'

services:

  api:
    image: vieirafelipe/vepilef
    ports:
      - "9000:9000"
    restart: on-failure:6 
    links:
      - mysql
    depends_on:
        mysql:
            condition: service_healthy
      

  mysql:
    image: vieirafelipe/vepilefmysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: Rr123
       MYSQL_USER: root
       MYSQL_DATABASE: plaform
       MYSQL_PASSWORD: Rr123
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
